# Generated by Django 3.1.3 on 2021-09-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='assets/videos')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_video', to='schProfile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('rating', models.CharField(blank=True, max_length=250, null=True)),
                ('review', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='schProfile.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PrincipalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('display_image', models.FileField(upload_to='assests/principal')),
                ('post_held', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='principal_detail', to='schProfile.profile')),
            ],
            options={
                'ordering': ('-principal_name',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='assets/sch-gallery')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='schProfile.profile')),
            ],
            options={
                'verbose_name': 'School Gallery',
                'verbose_name_plural': ' School Galleries',
                'ordering': ('-school',),
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_form', models.FileField(upload_to='sch-detail/addmission-leta')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='schProfile.profile')),
            ],
        ),
    ]
