# Generated by Django 3.1.3 on 2021-07-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='schoolvideo',
            options={},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='name',
        ),
    ]
