# Generated by Django 3.1.3 on 2021-08-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
