# Generated by Django 3.1.3 on 2021-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetail', '0002_auto_20210730_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='educational_rating',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='extral_curriculum_rating',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='services_rating',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
