# Generated by Django 3.1.3 on 2021-08-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetail', '0002_delete_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
