# Generated by Django 3.1.3 on 2021-08-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetail', '0003_delete_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer_email',
        ),
    ]
