# Generated by Django 3.1.3 on 2021-08-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetail', '0003_auto_20210802_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='educational_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='extral_curriculum_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='services_rating',
        ),
    ]
