# Generated by Django 3.1.3 on 2021-09-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetail', '0005_auto_20210816_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.FileField(upload_to='assets/sch-gallery'),
        ),
    ]
