# Generated by Django 3.1.3 on 2021-09-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0002_profile_view_count'),
        ('schoolDetail', '0006_auto_20210918_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='schProfile.profile'),
        ),
    ]
