# Generated by Django 3.1.3 on 2021-10-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetail', '0007_auto_20210918_1347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
