# Generated by Django 3.1.3 on 2020-11-19 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(blank=True, max_length=255, null=True)),
                ('school_badge', models.ImageField(blank=True, null=True, upload_to='profile/badge')),
                ('school_gender', models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('Mixed', 'Mixed')], max_length=255, null=True)),
                ('school_type', models.CharField(blank=True, choices=[('Day', 'Day'), ('Boarding', 'Boarding'), ('Mixed', 'Mixed')], max_length=255, null=True)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('extral_curriculum_activities', models.TextField(blank=True, null=True)),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='profile/video')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_tel', models.CharField(blank=True, max_length=150, null=True)),
                ('school_curriculum', models.CharField(blank=True, max_length=255, null=True)),
                ('schoolfees_range', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Profile',
                'verbose_name_plural': 'School Profiles',
                'ordering': ('-schoolName',),
            },
        ),
    ]
