# Generated by Django 3.1.3 on 2020-11-28 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='schoolProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('badge', models.ImageField(blank=True, null=True, upload_to='assets/badge')),
                ('schoolType', models.CharField(choices=[('Boarding', 'Boarding'), ('Day', 'Day'), ('Both', 'Both')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=20)),
                ('level', models.CharField(choices=[('Pri', 'Primary'), ('Sec', 'Secondary'), ('Both', 'Both')], max_length=40)),
                ('introVideo', models.FileField(blank=True, null=True, upload_to='assets/videos')),
                ('state', models.CharField(max_length=100)),
                ('curriculum', models.CharField(max_length=255)),
                ('extraCurriculumActivities', models.TextField()),
                ('phoneNumber', models.CharField(max_length=25)),
                ('schoolEmail', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('clubs', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Profile',
                'verbose_name_plural': 'School Profile',
                'ordering': ('school_name', 'created'),
            },
        ),
    ]
