# Generated by Django 3.1.3 on 2021-05-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school_facilities',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
