# Generated by Django 3.1.3 on 2020-11-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'ordering': ('-school_name',), 'verbose_name': 'School Profile', 'verbose_name_plural': 'School Profiles'},
        ),
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='user',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='schoolName',
            new_name='school_name',
        ),
    ]
