# Generated by Django 3.1.3 on 2020-12-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='date_established',
            field=models.DateField(blank=True, null=True),
        ),
    ]
