# Generated by Django 3.1.3 on 2021-06-01 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='school_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='badge',
            new_name='school_badge',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='clubs',
            new_name='school_clubs',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='curriculum',
            new_name='school_curriculum',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gender',
            new_name='school_gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='level',
            new_name='school_level',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='motto',
            new_name='school_motto',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='school_state',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='school_website',
        ),
    ]
