# Generated by Django 3.1.3 on 2020-12-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='schoolType',
            new_name='school_type',
        ),
    ]
