# Generated by Django 3.1.3 on 2021-07-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='competitive_advantage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
