# Generated by Django 3.1.3 on 2021-08-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
