# Generated by Django 3.1.3 on 2020-12-06 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0002_auto_20201206_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='awards_won',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='date_established',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='motto',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='schoo_fees_range',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
