# Generated by Django 3.1.3 on 2021-05-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0002_profile_school_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_established',
            field=models.DateField(blank=True, null=True),
        ),
    ]
