# Generated by Django 3.1.3 on 2020-12-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schProfile', '0003_auto_20201206_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='schoo_fees_range',
            new_name='school_fees_range',
        ),
    ]
